#include "jit.h"

OpcodeDef opcode_defs_brx[16] = {
        {"LBX", OPC_BRX_LBX, 3, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_LOAD, AM_BASE_REL_IDX_BX, OPERAND_INT16, "Single precision load, Base Relative Indexed"},
        {"DLBX", OPC_BRX_DLBX, 3, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_LOAD, AM_BASE_REL_IDX_BX, OPERAND_INT32, "Double precision load, Base Relative Indexed"},
        {"STBX", OPC_BRX_STBX, 3, CS_RW_NN,  false, true, true, false, IF_BASE_REL_INDX, OP_STORE, AM_BASE_REL_IDX_BX, OPERAND_INT16, "Single precision store, Base Relative Indexed"},
        {"DSTX", OPC_BRX_DSTX, 3, CS_RW_NN,  false, true, true, false, IF_BASE_REL_INDX, OP_STORE, AM_BASE_REL_IDX_BX, OPERAND_INT32, "Double precision store, Base Relative Indexed"},
        {"ABX", OPC_BRX_ABX, 4, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_ADD, AM_BASE_REL_IDX_BX, OPERAND_INT16, "Single precision integer add, Base Relative Indexed"},
        {"SBBX", OPC_BRX_SBBX, 4, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_SUB, AM_BASE_REL_IDX_BX, OPERAND_INT16, "Single precision integer subtract, Base Relative Indexed"},
        {"MBX", OPC_BRX_MBX, 5, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_MULT_PROD32, AM_BASE_REL_IDX_BX, OPERAND_INT16, "Single precision integer multiply with 32-bit product, Base Relative Indexed"},
        {"DBX", OPC_BRX_DBX, 5, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_DIV_REM_32_16, AM_BASE_REL_IDX_BX, OPERAND_INT16, "Single precision integer divide with 32-bit dividend, 16-bit divisor, Base Relative Indexed"},
        {"FABX", OPC_BRX_FABX, 6, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_ADD_FLOAT, AM_BASE_REL_IDX_BX, OPERAND_FLOAT, "Floating Point Add, Base Relative Indexed"},
        {"FSBX", OPC_BRX_FSBX, 6, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_SUB_FLOAT, AM_BASE_REL_IDX_BX, OPERAND_FLOAT, "Floating Point Subtract, Base Relative Indexed"},
        {"FMBX", OPC_BRX_FMBX, 6, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_MULT_FLOAT, AM_BASE_REL_IDX_BX, OPERAND_FLOAT, "Floating Point Multiply, Base Relative Indexed"},
        {"FDBX", OPC_BRX_FDBX, 7, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_DIV_FLOAT, AM_BASE_REL_IDX_BX, OPERAND_FLOAT, "Floating Point Divide, Base Relative Indexed"},
        {"CBX", OPC_BRX_CBX, 3, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_COMPARE, AM_BASE_REL_IDX_BX, OPERAND_INT16, "Single precision Compare, Base Relative Indexed"},
        {"FCBX", OPC_BRX_FCBX, 6, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_COMPARE_FLOAT, AM_BASE_REL_IDX_BX, OPERAND_FLOAT, "Floating Point Compare, Base Relative Indexed"},
        {"ANDX", OPC_BRX_ANDX, 3, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_AND, AM_BASE_REL_IDX_BX, OPERAND_INT16, "Logical AND, Base Relative Indexed"},
        {"ORBX", OPC_BRX_ORBX, 3, CS_W_ALL,  false, true, true, false, IF_BASE_REL_INDX, OP_OR, AM_BASE_REL_IDX_BX, OPERAND_INT16, "Logical OR, Base Relative Indexed"},
};

OpcodeDef opcode_defs_imm[16] = {
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"AIM", OPC_IMM_AIM, 2, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_ADD, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Single precision integer add, Immediate"},
        {"SIM", OPC_IMM_SIM, 2, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_SUB, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Single precision integer subtract, Immediate"},
        {"MIM", OPC_IMM_MIM, 3, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_MULT_PROD32, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Single precision integer multiply with 32-bit product, Immediate"},
        {"MSIM", OPC_IMM_MSIM, 4, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_MULT_PROD16, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Single precision integer multiply with 16-bit product, Immediate"},
        {"DIM", OPC_IMM_DIM, 4, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_DIV_REM_32_16, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Single precision integer divide with 32-bit dividend, Immediate"},
        {"DVIM", OPC_IMM_DVIM, 5, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_DIV_REM_16_16, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Single precision integer divide with 16-bit dividend, Immediate"},
        {"ANDM", OPC_IMM_ANDM, 3, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_AND, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Logical AND, Immediate"},
        {"ORIM", OPC_IMM_ORIM, 3, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_OR, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Inclusive logical OR, Immediate"},
        {"XORM", OPC_IMM_XORM, 3, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_XOR, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Exclusive logical OR, Immediate"},
        {"CIM", OPC_IMM_CIM, 3, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_COMPARE, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Single precision compare, Immediate"},
        {"NIM", OPC_IMM_NIM, 3, CS_W_ALL,  false, true, true, true, IF_IMMEDIATE, OP_NAND, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Logical NAND, Immediate"},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
};
/* 0x00 - 0x43 */
OpcodeDef opcode_defs_6bit[17] = {
        /* 00 - 3F */
        {"LB", OPC_LB, 3, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_LOAD, AM_BASE_REL_B, OPERAND_INT16, "Single precision load, Base Relative"},
        {"DLB", OPC_DLB, 3, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_LOAD, AM_BASE_REL_B, OPERAND_INT32, "Double precision load, Base Relative"},
        {"STB", OPC_STB, 3, CS_RW_NN,  false, true, true, false, IF_BASE_RELATIVE, OP_STORE, AM_BASE_REL_B, OPERAND_INT16, "Single precision store, Base Relative"},
        {"DSTB", OPC_DSTB, 3, CS_RW_NN,  false, true, true, false, IF_BASE_RELATIVE, OP_STORE, AM_BASE_REL_B, OPERAND_INT32, "Double precision store, Base Relative"},
        {"AB", OPC_AB, 4, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_ADD, AM_BASE_REL_B, OPERAND_INT16, "Single precision integer add, Base Relative"},
        {"SBB", OPC_SBB, 4, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_SUB, AM_BASE_REL_B, OPERAND_INT16, "Single precision integer subtract, Base Relative"},
        {"MB", OPC_MB, 5, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_MULT_PROD32, AM_BASE_REL_B, OPERAND_INT16, "Single precision integer multiply with 32-bit product, Base Relative"},
        {"DB", OPC_DB, 5, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_DIV_REM_32_16, AM_BASE_REL_B, OPERAND_INT16, "Single precision integer divide with 32-bit dividend, Base Relative"},
        {"FAB", OPC_FAB, 6, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_ADD_FLOAT, AM_BASE_REL_B, OPERAND_FLOAT, "Floating point add, Base Relative"},
        {"FSB", OPC_FSB, 6, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_SUB_FLOAT, AM_BASE_REL_B, OPERAND_FLOAT, "Floating point subtract, Base Relative"},
        {"FMB", OPC_FMB, 6, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_MULT_FLOAT, AM_BASE_REL_B, OPERAND_FLOAT, "Floating point multiply, Base Relative"},
        {"FDB", OPC_FDB, 7, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_DIV_FLOAT, AM_BASE_REL_B, OPERAND_FLOAT, "Floating point divide, Base Relative"},
        {"ORB", OPC_ORB, 3, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_OR, AM_BASE_REL_B, OPERAND_INT16, "Inclusive logical OR, Base Relative"},
        {"ANDB", OPC_ANDB, 3, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_AND, AM_BASE_REL_B, OPERAND_INT16, "Logical AND, Base Relative"},
        {"CB", OPC_CB, 3, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_COMPARE, AM_BASE_REL_B, OPERAND_INT16, "Single precision compare, Base Relative"},
        {"FCB", OPC_FCB, 6, CS_W_ALL,  false, true, true, false, IF_BASE_RELATIVE, OP_COMPARE_FLOAT, AM_BASE_REL_B, OPERAND_FLOAT, "Floating point compare, Base Relative"},
        {"BRX", OPC_BRX, 3, CS_RW_NN,  false, true, true, false, IF_BASE_REL_INDX, OP_SPECIAL, AM_BASE_REL_IDX_BX} /*special -
        becomes LBX, DLBX, STBX, DSTX, ABX, SBBX, MBX, DBX,
                FABX, FSBX, FMBX, FDBX, CBX, FCBX, ANDX, ORBX */
};
/* starting from 0x44 */
OpcodeDef opcode_defs_8bit[188] = {
        /* 44 - 4F */
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"XIO", OPC_XIO, 0, CS_RW_NN,  false, true, true, true, IF_LONG, OP_XIO, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Execute input/output"}, /* 0x48 */ /* we can jit it actually if RX is 0 */
        {"VIO", OPC_VIO, 0, CS_RW_NN,  false, false, true, true, IF_LONG, OP_XIO, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Vectored input/output"}, /* 0x49 */
        {"IMM", OPC_IMM, 0, CS_RW_NN,  false, false, true, false}, /* 0x4A */ /* special, see opcode_defs_imm */
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false}, /* 0x4B */
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false}, /* 0x4C */
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false}, /* 0x4D */
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false}, /* 0x4E */
        {"BIF", OPC_BIF, 2, CS_W_ALL,  false, false, true, false, IF_SPECIAL, OP_SPECIAL, AM_SPECIAL_S, OPERAND_INT16, "Built-In-Function"}, /* 0x4F */ /* not jitable */


            /* 50 - 5F */
        {"SB", OPC_SB, 2, CS_RW_NN,  true, true, true, true, IF_CONST_LONG, OP_SET_BIT, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Set bit"},
        {"SBR", OPC_SBR, 2, CS_RW_NN,  true, true, true, false, IF_CONST_REG, OP_SET_BIT, AM_REG_DIRECT_R, OPERAND_INT16, "Set bit, Register"},
        {"SBI", OPC_SBI, 2, CS_RW_NN,  true, true, true, true, IF_CONST_LONG, OP_SET_BIT, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Set bit, Indirect"},
        {"RB", OPC_RB, 2, CS_RW_NN,  true, true, true, true, IF_CONST_LONG, OP_RESET_BIT, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Reset bit"},
        {"RBR", OPC_RBR, 2, CS_RW_NN,  true, true, true, false, IF_CONST_REG, OP_RESET_BIT, AM_REG_DIRECT_R, OPERAND_INT16, "Reset bit, Register"},
        {"RBI", OPC_RBI, 2, CS_RW_NN,  true, true, true, true, IF_CONST_LONG, OP_RESET_BIT, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Reset bit, Indirect"},
        {"TB", OPC_TB, 2, CS_W_ALL,  true, true, true, true, IF_CONST_LONG, OP_TEST_BIT, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Test bit"},
        {"TBR", OPC_TBR, 2, CS_W_ALL,  true, true, true, false, IF_CONST_REG, OP_TEST_BIT, AM_REG_DIRECT_R, OPERAND_INT16, "Test bit, Register"},
        {"TBI", OPC_TBI, 2, CS_W_ALL,  true, true, true, true, IF_CONST_LONG, OP_TEST_BIT, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Test bit, Indirect"},
        {"TSB", OPC_TSB, 2, CS_W_ALL,  true, true, true, true, IF_CONST_LONG, OP_TEST_SET_BIT, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Test and set bit"},
        {"SVBR", OPC_SVBR, 2, CS_RW_NN,  true, true, true, false, IF_REG_REG, OP_SET_VAR_BIT, AM_REG_DIRECT_R, OPERAND_INT16, "Set variable bit in register"},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},

        {"RVBR", OPC_RVBR, 2, CS_RW_NN,  true, true, true, false, IF_REG_REG, OP_RESET_VAR_BIT, AM_REG_DIRECT_R, OPERAND_INT16, "Reset variable bit in register"},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"TVBR", OPC_TVBR, 2, CS_W_ALL,  true, true, true, false, IF_REG_REG, OP_TEST_VAR_BIT, AM_REG_DIRECT_R, OPERAND_INT16, "Test variable bit in register"},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},

        /* 60 - 6F */
        {"SLL", OPC_SLL, 2, CS_W_ALL,  false, true, true, false, IF_CONST_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT16, "Shift left logical"},
        {"SRL", OPC_SRL, 2, CS_W_ALL,  false, true, true, false, IF_CONST_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT16, "Shift right logical"},
        {"SRA", OPC_SRA, 2, CS_W_ALL,  false, true, true, false, IF_CONST_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT16, "Shift right arithmetic"},
        {"SLC", OPC_SLC, 2, CS_W_ALL,  false, true, true, false, IF_CONST_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT16, "Shift left cyclic"},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"DSLL", OPC_DSLL, 3, CS_W_ALL,  false, true, true, false, IF_CONST_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT32, "Double shift left logical"},
        {"DSRL", OPC_DSRL, 3, CS_W_ALL,  false, true, true, false, IF_CONST_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT32, "Double shift right logical"},
        {"DSRA", OPC_DSRA, 3, CS_W_ALL,  false, true, true, false, IF_CONST_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT32, "Double shift right arithmetic"},
        {"DSLC", OPC_DSLC, 3, CS_W_ALL,  false, true, true, false, IF_CONST_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT32, "Double shift left cyclic"},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"SLR", OPC_SLR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT16, "Shift logical, count in register"},
        {"SAR", OPC_SAR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT16, "Shift arithmetic, count in register"},
        {"SCR", OPC_SCR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT16, "Shift cyclic, count in register"},
        {"DSLR", OPC_DSLR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT32, "Double shift logical, count in register"},
        {"DSAR", OPC_DSAR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT32, "Double shift arithmetic, count in register"},
        {"DSCR", OPC_DSCR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SHIFT, AM_REG_DIRECT_R, OPERAND_INT32, "Double shift cyclic, count in register"},

        /* 70 - 7F */
        {"JC", OPC_JC, 2, CS_R_ALL,  true, true, true, true, IF_CONST_LONG, OP_JUMP_COND, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Jump on condition"}, /* we can jit it only if RX is 0*/
        {"JCI", OPC_JCI, 2, CS_R_ALL,  true, false, true, true, IF_CONST_LONG, OP_JUMP_COND, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Jump on condition, Indirect"}, /* we cannot jit it */
        {"JS", OPC_JS, 2, CS_RW_NN,  true, false, true, true, IF_LONG, OP_JUMP_SUBRTN, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Jump to subroutine"}, /* we can jit it only if RX is 0*/
        {"SOJ", OPC_SOJ, 2, CS_W_ALL,  true, true, true, true, IF_LONG, OP_SUBTR_JUMP, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Subtract one and jump"}, /* we can jit it only if RX is 0*/
        {"BR", OPC_BR, 2, CS_RW_NN,  true, true, true, false, IF_COUNTER_RELATIVE, OP_BRANCH, AM_CNT_REL_ICR, OPERAND_INT16, "Branch unconditionally"},
        {"BEZ", OPC_BEZ, 2, CS_R_Z,  true, true, true, false, IF_COUNTER_RELATIVE, OP_BRANCH, AM_CNT_REL_ICR, OPERAND_INT16, "Branch if equal to (zero)"},
        {"BLT", OPC_BLT, 2, CS_R_N,  true, true, true, false, IF_COUNTER_RELATIVE, OP_BRANCH, AM_CNT_REL_ICR, OPERAND_INT16, "Branch if less than (zero)"},
        {"BEX", OPC_BEX, 2, CS_W_ALL,  true, false, true, false, IF_REG_CONST, OP_BR_EXECUTIVE, AM_SPECIAL_S, OPERAND_INT16, "Branch to executive"}, /* we can jit it only if RX is 0*/
        {"BLE", OPC_BLE, 2, CS_R_NZ,  true, true, true, false, IF_COUNTER_RELATIVE, OP_BRANCH, AM_CNT_REL_ICR, OPERAND_INT16, "Branch if less than or equal to (zero)"},
        {"BGT", OPC_BGT, 2, CS_R_P,  true, true, true, false, IF_COUNTER_RELATIVE, OP_BRANCH, AM_CNT_REL_ICR, OPERAND_INT16, "Branch if greater than (zero)"},
        {"BNZ", OPC_BNZ, 2, CS_R_Z,  true, true, true, false, IF_COUNTER_RELATIVE, OP_BRANCH, AM_CNT_REL_ICR, OPERAND_INT16, "Branch if not equal to (zero)"},
        {"BGE", OPC_BGE, 2, CS_R_PZ,  true, true, true, false, IF_COUNTER_RELATIVE, OP_BRANCH, AM_CNT_REL_ICR, OPERAND_INT16, "Branch if greater than or equal to (zero)"},
        {"LSTI", OPC_LSTI, 2, CS_W_ALL,  true, false, true, true, IF_CONST_LONG, OP_LOAD_STATUS, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Load status, Indirect"},
        {"LST", OPC_LST, 2, CS_W_ALL,  true, false, true, true, IF_CONST_LONG, OP_LOAD_STATUS, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Load status"},
        {"SJS", OPC_SJS, 2, CS_RW_NN,  true, true, true, true, IF_LONG, OP_JUMP_SUBRTN, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Stack IC and jump to subroutine"}, /* we can jit it only if RX is 0*/
        {"URS", OPC_URS, 2, CS_RW_NN,  true, true, true, false, IF_REG_CONST, OP_RET_SUBRTN, AM_SPECIAL_S, OPERAND_INT16, "Unstack IC and return from subroutine"},
        /* 80 - 8F */
        {"L", OPC_L, 2, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Single precision load"},
        {"LR", OPC_LR, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_LOAD, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision load, Register"},
        {"LISP", OPC_LISP, 2, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_LOAD, AM_IMM_SHRT_POS_ISP, OPERAND_INT16, "Single precision load, Immediate Short Positive"},
        {"LISN", OPC_LISN, 2, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_LOAD, AM_IMM_SHRT_NEG_ISN, OPERAND_INT16, "Single precision load, Immediate Short Negative"},
        {"LI", OPC_LI, 2, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Single precision load, Indirect"},
        {"LIM", OPC_LIM, 2, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD, AM_IMM_LONG_IM_IMX, OPERAND_INT16, "Single precision load, Immediate"},
        {"DL", OPC_DL, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD, AM_MEM_DIRECT_D_DX, OPERAND_INT32, "Double precision load"},
        {"DLR", OPC_DLR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_LOAD, AM_REG_DIRECT_R, OPERAND_INT32, "Double precision load, Register"},
        {"DLI", OPC_DLI, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD, AM_MEM_INDIRECT_I_IX, OPERAND_INT32, "Double precision load, Indirect"},
        {"LM", OPC_LM, 3, CS_RW_NN,  false, true, true, true, IF_CONST_LONG, OP_MULT_REG, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Load multiple registers"},
        {"EFL", OPC_EFL, 2, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD, AM_MEM_DIRECT_D_DX, OPERAND_EXFLOAT, "Extended precision floating point load"},
        {"LUB", OPC_LUB, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD_BYTE, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Load from upper byte"},
        {"LLB", OPC_LLB, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD_BYTE, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Load from lower byte"},
        {"LUBI", OPC_LUBI, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD_BYTE, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Load from upper byte, Indirect"},
        {"LLBI", OPC_LLBI, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_LOAD_BYTE, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Load from lower byte, Indirect"},
        {"POPM", OPC_POPM, 3, CS_RW_NN,  false, true, true, false, IF_CONST_LONG, OP_MULT_REG, AM_SPECIAL_S, OPERAND_INT16, "Pop multiple registers off the stack"},
        /* 90 - 9F */
        {"ST", OPC_ST, 2, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Single precision store"},
        {"STC", OPC_STC, 3, CS_RW_NN,  false, true, true, true, IF_CONST_LONG, OP_STORE, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Store a non-negative constant"},
        {"STCI", OPC_STCI, 3, CS_RW_NN,  false, true, true, true, IF_CONST_LONG, OP_STORE, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Store a non-negative constant, Indirect"},
        {"MOV", OPC_MOV, 2, CS_RW_NN,  false, true, true, false, IF_REG_REG, OP_MOVE, AM_SPECIAL_S, OPERAND_INT16, "Move multiple words, memory-to-memory"},
        {"STI", OPC_STI, 2, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Single precision store, Indirect"},
        {"ILLEGAL", OPC_ILLEGAL, 0, CS_RW_NN,  false, false, false, false},
        {"DST", OPC_DST, 3, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE, AM_MEM_DIRECT_D_DX, OPERAND_INT32, "Double precision store"},
        {"SRM", OPC_SRM, 3, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE_MASK, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Store register through mask"},
        {"DSTI", OPC_DSTI, 3, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE, AM_MEM_INDIRECT_I_IX, OPERAND_INT32, "Double precision store, Indirect"},
        {"STM", OPC_STM, 3, CS_RW_NN,  false, true, true, true, IF_CONST_LONG, OP_MULT_REG, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Store multiple registers"},
        {"EFST", OPC_EFST, 3, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE, AM_MEM_DIRECT_D_DX, OPERAND_EXFLOAT, "Extended precision floating point store"},
        {"STUB", OPC_STUB, 3, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE_BYTE, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Store into upper byte"},
        {"STLB", OPC_STLB, 3, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE_BYTE, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Store into lower byte"},
        {"SUBI", OPC_SUBI, 2, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE_BYTE, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Store into upper byte, Indirect"},
        {"SLBI", OPC_SLBI, 3, CS_RW_NN,  false, true, true, true, IF_LONG, OP_STORE_BYTE, AM_MEM_INDIRECT_I_IX, OPERAND_INT16, "Store into lower byte, Indirect"},
        {"PSHM", OPC_PSHM, 3, CS_RW_NN,  false, true, true, false, IF_REG_REG, OP_MULT_REG, AM_SPECIAL_S, OPERAND_INT16, "Push multiple registers onto the stack"},
        /* A0 - AF */ /* ADDITION/ ABSOLUTE*/
        {"A", OPC_A, 2, CS_W_ALL,  false, true, true, true, IF_LONG, OP_ADD, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Single precision integer add"},
        {"AR", OPC_AR, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_ADD, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision integer add, Register"},
        {"AISP", OPC_AISP, 2, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_ADD, AM_IMM_SHRT_POS_ISP, OPERAND_INT16, "Single precision integer add, Immediate Short Positive"},
        {"INCM", OPC_INCM, 2, CS_W_ALL,  false, true, true, true, IF_CONST_LONG, OP_INC_DEC_MEM, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Increment memory by a positive integer"},
        {"ABS", OPC_ABS, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_ABS, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision absolute value of register"},
        {"DABS", OPC_DABS, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_ABS, AM_REG_DIRECT_R, OPERAND_INT32, "Double precision absolute value of register"},
        {"DA", OPC_DA, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_ADD, AM_MEM_DIRECT_D_DX, OPERAND_INT32, "Double precision integer add"},
        {"DAR", OPC_DAR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_ADD, AM_REG_DIRECT_R, OPERAND_INT32, "Double precision integer add, Register"},
        {"FA", OPC_FA, 6, CS_W_ALL,  false, true, true, true, IF_LONG, OP_ADD_FLOAT, AM_MEM_DIRECT_D_DX, OPERAND_FLOAT, "Floating point add"},
        {"FAR", OPC_FAR, 6, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_ADD_FLOAT, AM_REG_DIRECT_R, OPERAND_FLOAT, "Floating point add, Register"},
        {"EFA", OPC_EFA, 6, CS_W_ALL,  false, true, true, true, IF_LONG, OP_ADD_EXFLOAT, AM_MEM_DIRECT_D_DX, OPERAND_EXFLOAT, "Extended precision floating point add"},
        {"EFAR", OPC_EFAR, 6, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_ADD_EXFLOAT, AM_REG_DIRECT_R, OPERAND_EXFLOAT, "Extended precision floating point add, Register"},
        {"FABS", OPC_FABS, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_ABS_FLOAT, AM_REG_DIRECT_R, OPERAND_FLOAT, "Floating point absolute value of register"},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        /* B0 - BF */ /* SUBTRACTION/ NEGATION */
        {"S", OPC_S, 2, CS_W_ALL,  false, true, true, true, IF_LONG, OP_SUB, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Single precision integer subtract"},
        {"SR", OPC_SR, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SUB, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision integer subtract, Register"},
        {"SISP", OPC_SISP, 2, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_SUB, AM_IMM_SHRT_POS_ISP, OPERAND_INT16, "Single precision integer subtract, Immediate Short Positive"},
        {"DECM", OPC_DECM, 2, CS_W_ALL,  false, true, true, true, IF_CONST_LONG, OP_INC_DEC_MEM, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Decrement memory by a positive integer"},
        {"NEG", OPC_NEG, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_NEG, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision negate register"},
        {"DNEG", OPC_DNEG, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_NEG, AM_REG_DIRECT_R, OPERAND_INT32, "Double precision negate register"},
        {"DS", OPC_DS, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_SUB, AM_MEM_DIRECT_D_DX, OPERAND_INT32, "Double precision integer subtract"},
        {"DSR", OPC_DSR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SUB, AM_REG_DIRECT_R, OPERAND_INT32, "Double precision integer subtract, Register"},
        {"FS", OPC_FS, 6, CS_W_ALL,  false, true, true, true, IF_LONG, OP_SUB_FLOAT, AM_MEM_DIRECT_D_DX, OPERAND_FLOAT, "Floating point subtract"},
        {"FSR", OPC_FSR, 6, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SUB_FLOAT, AM_REG_DIRECT_R, OPERAND_FLOAT, "Floating point subtract, Register"},
        {"EFS", OPC_EFS, 6, CS_W_ALL,  false, true, true, true, IF_LONG, OP_SUB_EXFLOAT, AM_MEM_DIRECT_D_DX, OPERAND_EXFLOAT, "Extended precision floating point subtract"},
        {"EFSR", OPC_EFSR, 6, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_SUB_EXFLOAT, AM_REG_DIRECT_R, OPERAND_EXFLOAT, "Extended precision floating point subtract, Register"},
        {"FNEG", OPC_FNEG, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_NEG_FLOAT, AM_REG_DIRECT_R, OPERAND_FLOAT, "Floating point negate register"},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        /* C0 - CF */ /* MULTIPLICATION */
        {"MS", OPC_MS, 7, CS_W_ALL,  false, true, true, true, IF_LONG, OP_MULT_PROD16, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Single precision integer multiply with 16-bit product"},
        {"MSR", OPC_MSR, 7, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_MULT_PROD16, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision integer multiply with 16-bit product, Register"},
        {"MISP", OPC_MISP, 7, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_MULT_PROD16, AM_IMM_SHRT_POS_ISP, OPERAND_INT16, "Single precision integer multiply with 16-bit product, Immediate Short Positive"},
        {"MISN", OPC_MISN, 7, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_MULT_PROD16, AM_IMM_SHRT_NEG_ISN, OPERAND_INT16, "Single precision integer multiply with 16-bit product, Immediate Short Negative"},
        {"M", OPC_M, 7, CS_W_ALL,  false, true, true, true, IF_LONG, OP_MULT_PROD32, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Single precision integer multiply with 32-bit product"},
        {"MR", OPC_MR, 7, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_MULT_PROD32, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision integer multiply with 32-bit product, Register"},
        {"DM", OPC_DM, 7, CS_W_ALL,  false, true, true, true, IF_LONG, OP_DMULT_PROD32, AM_MEM_DIRECT_D_DX, OPERAND_INT32, "Double precision integer multiply"},
        {"DMR", OPC_DMR, 7, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_DMULT_PROD32, AM_REG_DIRECT_R, OPERAND_INT32, "Double precision integer multiply, Register"},
        {"FM", OPC_FM, 8, CS_W_ALL,  false, true, true, true, IF_LONG, OP_MULT_FLOAT, AM_MEM_DIRECT_D_DX, OPERAND_FLOAT, "Floating point multiply"},
        {"FMR", OPC_FMR, 8, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_MULT_FLOAT, AM_REG_DIRECT_R, OPERAND_FLOAT, "Floating point multiply, Register"},
        {"EFM", OPC_EFM, 8, CS_W_ALL,  false, true, true, true, IF_LONG, OP_MULT_EXFLOAT, AM_MEM_DIRECT_D_DX, OPERAND_EXFLOAT, "Extended precision floating point multiply"},
        {"EFMR", OPC_EFMR, 8, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_MULT_EXFLOAT, AM_REG_DIRECT_R, OPERAND_EXFLOAT, "Extended precision floating point multiply, Register"},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        /* D0 - DF */ /* DIVISION */
        {"DV", OPC_DV, 8, CS_W_ALL,  false, true, true, true, IF_LONG, OP_DIV_REM_16_16, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Single precision integer divide with 16-bit dividend"},
        {"DVR", OPC_DVR, 8, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_DIV_REM_16_16, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision integer divide with 16-bit dividend, Register"},
        {"DISP", OPC_DISP, 8, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_DIV_REM_16_16, AM_IMM_SHRT_POS_ISP, OPERAND_INT16, "Single precision integer divide with 16-bit dividend, Immediate Short Positive"},
        {"DISN", OPC_DISN, 8, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_DIV_REM_16_16, AM_IMM_SHRT_NEG_ISN, OPERAND_INT16, "Single precision integer divide with 16-bit dividend, Immediate Short Negative"},
        {"D", OPC_D, 8, CS_W_ALL,  false, true, true, true, IF_LONG, OP_DIV_REM_32_16, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Single precision integer divide with 32-bit dividend"},
        {"DR", OPC_DR, 8, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_DIV_REM_32_16, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision integer divide with 32-bit dividend, Register"},
        {"DD", OPC_DD, 8, CS_W_ALL,  false, true, true, true, IF_LONG, OP_DIV_32_32, AM_MEM_DIRECT_D_DX, OPERAND_INT32, "Double precision integer divide"},
        {"DDR", OPC_DDR, 8, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_DIV_32_32, AM_REG_DIRECT_R, OPERAND_INT32, "Double precision integer divide, Register"},
        {"FD", OPC_FD, 8, CS_W_ALL,  false, true, true, true, IF_LONG, OP_DIV_FLOAT, AM_MEM_DIRECT_D_DX, OPERAND_FLOAT, "Floating point divide"},
        {"FDR", OPC_FDR, 8, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_DIV_FLOAT, AM_REG_DIRECT_R, OPERAND_FLOAT, "Floating point divide, Register"},
        {"EFD", OPC_EFD, 8, CS_W_ALL,  false, true, true, true, IF_LONG, OP_DIV_EXFLOAT, AM_MEM_DIRECT_D_DX, OPERAND_EXFLOAT, "Extended precision floating point divide"},
        {"EFDR", OPC_EFDR, 8, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_DIV_EXFLOAT, AM_REG_DIRECT_R, OPERAND_EXFLOAT, "Extended precision floating point divide, Register"},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        /* E0 - EF */ /* LOGICAL OPERATIONS */
        {"OR", OPC_OR, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_OR, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Inclusive logical OR"},
        {"ORR", OPC_ORR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_OR, AM_REG_DIRECT_R, OPERAND_INT16, "Inclusive logical OR, Register"},
        {"AND", OPC_AND, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_AND, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Logical AND"},
        {"ANDR", OPC_ANDR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_AND, AM_REG_DIRECT_R, OPERAND_INT16, "Logical AND, Register"},
        {"XOR", OPC_XOR, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_XOR, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Exclusive logical OR"},
        {"XORR", OPC_XORR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_XOR, AM_REG_DIRECT_R, OPERAND_INT16, "Exclusive logical OR, Register"},
        {"N", OPC_N, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_NAND, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Logical NAND"},
        {"NR", OPC_NR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_NAND, AM_REG_DIRECT_R, OPERAND_INT16, "Logical NAND, Register"},
        /* FLOAT CONVERSION */
        {"FIX", OPC_FIX, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_FLT_TO_INT16, AM_REG_DIRECT_R, OPERAND_FLOAT, "Convert floating point to 16-bit integer"},
        {"FLT", OPC_FLT, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_INT16_TO_FLT, AM_REG_DIRECT_R, OPERAND_FLOAT, "Convert 16-bit integer to floating point"},
        {"EFIX", OPC_EFIX, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_EFLT_TO_INT32, AM_REG_DIRECT_R, OPERAND_EXFLOAT, "Convert extended precision floating point to 32-bit integer"},
        {"EFLT", OPC_EFLT, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_INT32_TO_EFLT, AM_REG_DIRECT_R, OPERAND_EXFLOAT, "Convert 32-bit integer to extended precision floating point"},
        /* EXCHANGE */
        {"XBR", OPC_XBR, 2, CS_W_ALL,  true, true, true, false, IF_REG_CONST, OP_EXCHANGE_BYTE, AM_SPECIAL_S, OPERAND_INT16, "Exchange bytes in register"},
        {"XWR", OPC_XWR, 2, CS_W_ALL,  true, true, true, false, IF_REG_CONST, OP_EXCHANGE_WORD, AM_REG_DIRECT_R, OPERAND_INT16, "Exchange words in registers"},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        /* F0 - FF */ /* COMPARISON */
        {"C", OPC_C, 2, CS_W_ALL,  false, true, true, true, IF_LONG, OP_COMPARE, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Single precision compare"},
        {"CR", OPC_CR, 2, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_COMPARE, AM_REG_DIRECT_R, OPERAND_INT16, "Single precision compare, Register"},
        {"CISP", OPC_CISP, 2, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_COMPARE, AM_IMM_SHRT_POS_ISP, OPERAND_INT16, "Single precision compare, Immediate Short Positive"},
        {"CISN", OPC_CISN, 2, CS_W_ALL,  false, true, true, false, IF_REG_CONST, OP_COMPARE, AM_IMM_SHRT_NEG_ISN, OPERAND_INT16, "Single precision compare, Immediate Short Negative"},
        {"CBL", OPC_CBL, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_COMP_LIM, AM_MEM_DIRECT_D_DX, OPERAND_INT16, "Compare between limits"},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"DC", OPC_DC, 3, CS_W_ALL,  false, true, true, true, IF_LONG, OP_COMPARE, AM_MEM_DIRECT_D_DX, OPERAND_INT32, "Double precision compare"},
        {"DCR", OPC_DCR, 3, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_COMPARE, AM_REG_DIRECT_R, OPERAND_INT32, "Double precision compare, Register"},
        {"FC", OPC_FC, 6, CS_W_ALL,  false, true, true, true, IF_LONG, OP_COMPARE_FLOAT, AM_MEM_DIRECT_D_DX, OPERAND_FLOAT, "Floating point compare"},
        {"FCR", OPC_FCR, 6, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_COMPARE_FLOAT, AM_REG_DIRECT_R, OPERAND_FLOAT, "Floating point compare, Register"},
        {"EFC", OPC_EFC, 6, CS_W_ALL,  false, true, true, true, IF_LONG, OP_COMPARE_EXFLOAT, AM_MEM_DIRECT_D_DX, OPERAND_EXFLOAT, "Extended precision floating point compare"},
        {"EFCR", OPC_EFCR, 6, CS_W_ALL,  false, true, true, false, IF_REG_REG, OP_COMPARE_EXFLOAT, AM_REG_DIRECT_R, OPERAND_EXFLOAT, "Extended precision floating point compare, Register"},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"ILLEGAL", OPC_ILLEGAL, 0, 0x00,  false, false, false, false},
        {"NOP_BPT", OPC_NOP_BPT, 1, CS_RW_NN,  false, true, true, false, IF_SPECIAL, OP_EXTENSION, AM_SPECIAL_S, OPERAND_INT16, "No operation / Break point"} /* this is a special pseudo-opcode for JIT, it is not an actual opcode in the instruction set */

};